//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BD.BloodTransfusionCenter.Core
{
    public partial class BloodDonationPledgeExtended : EntityBase<Guid>, IAggregateRoot {

        public BloodDonationPledgeExtended()
        {
            OnCreated();
        }

        public Guid Id { get; set; }

        public BloodDonationPladgeEvolutionStatus EvolutionStatus { get; set; }

        public DateTime PledgeInitiatedDate { get; set; }

        public DateTime? PledgeEffectiveDate { get; set; }

        public DateTime? PledgeHonoredOrCanceledDate { get; set; }

        public string CantBeDoneReason { get; set; }

        public Guid DonorCorrelationId { get; set; }

        public string DonorName { get; set; }

        public DateTime DonorBirthDate { get; set; }

        public BloodGroup DonorBloodGroup { get; set; }

        public string DonorNIN { get; set; }

        public string DonorTel { get; set; }

        public string DonorEmail { get; set; }

        public string DonorNotes { get; set; }

        public DateTime? DonorLastDonationDate { get; set; }

        public Guid BloodDonationRequestId { get; set; }

        public virtual BloodDonationRequest BloodDonationRequest { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
