//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BD.BloodTransfusionCenter.Core
{
    public partial class BloodDonation : EntityBase<Guid>, IAggregateRoot {

        public BloodDonation()
        {
            OnCreated();
        }

        public Guid Id { get; set; }

        public BloodDonationStatus DonationStatus { get; set; }

        public DateTime DonationDate { get; set; }

        public BloodDonationType Type { get; set; }

        public BloodGroup? Group { get; set; }

        public string LotNumber { get; set; }

        public Guid DonorId { get; set; }

        public Guid? BloodDonationRequestId { get; set; }

        public virtual Donor Donor { get; set; }

        public virtual BloodDonationRequest BloodDonationRequest { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
