//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BD.BloodTransfusionCenter.Core
{
    public partial class Commune : EntityBase<int>, IAggregateRoot {

        public Commune()
        {
            this.Donors = new List<Donor>();
            OnCreated();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public int WilayaId { get; set; }

        public virtual Wilaya Wilaya { get; set; }

        public virtual IList<Donor> Donors { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
