//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BD.BloodTransfusionCenter.Core
{
    public partial class Donor : EntityBase<Guid>, IAggregateRoot {

        public Donor()
        {
            this.BloodDonations = new List<BloodDonation>();
            OnCreated();
        }

        public Guid Id { get; set; }

        public Guid? CorrelationId { get; set; }

        public string Name { get; set; }

        public DateTime BirthDate { get; set; }

        public BloodGroup BloodGroup { get; set; }

        public string NIN { get; set; }

        public string Tel { get; set; }

        public string Email { get; set; }

        public string NotesForBTC { get; set; }

        public DateTime? LastDonationDate { get; set; }

        public int CommuneId { get; set; }

        public virtual IList<BloodDonation> BloodDonations { get; set; }

        public virtual Commune Commune { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
