//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BD.BloodTransfusionCenter.Core
{
    public enum BloodDonationPladgeEvolutionStatus : int
    {
        Initiated = 0,
        Honored = 1,
        CanceledByInitiaor = 2,
        CanceledByServiceNotNeeded = 3,
        CanceledByServiceCantBeDone = 4,
        CanceledTimeout = 5
    }
}
