# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=57679


// List all contributors
GET {{host}}:{{port}}/Contributors

###
@id_to_get=2
GET {{host}}:{{port}}/Contributors/{{id_to_get}}

###
// Add a new contributor
POST {{host}}:{{port}}/Contributors
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "test@test.com",
  "phoneNumber": "1234567890"
}

###
@id_to_update=3
PUT {{host}}:{{port}}/Contributors/{{id_to_update}}
Content-Type: application/json

{
  "id": {{id_to_update}},
  "name": "ardalis2"
}

###
@id_to_delete=6
DELETE {{host}}:{{port}}/Contributors/{{id_to_delete}}

###



### Auth:

### Register:

POST {{host}}:{{port}}/auth/register2
Content-Type: application/json
{
  "userName": "walidozich123",
  "email": "walidozich123@example.com",
  "password": "vV@L1d@2002",
  "confirmPassword": "vV@L1d@2002",
  "donorWantToStayAnonymous": true,
  "donorExcludeFromPublicPortal": true,
  "donorAvailability": 1,
  "donorContactMethod": 1,
  "donorName": "CHERCHALI WALIDozich",
  "donorBirthDate": "2002-05-22T09:16:16.749Z",
  "donorBloodGroup": 2,
  "donorNIN": "123485489123456789",
  "donorTel": "0555052376",
  "donorNotesForBTC": "Rien",
  "donorLastDonationDate": "2025-05-17T09:16:16.749Z",
  "communeId": 558  
}
###

POST {{host}}:{{port}}/auth/register
Content-Type: application/json
{
  "userName": "hiki",
  "email": "hiki@example.com",
  "password": "Hiki-2025",
  "confirmPassword": "Hiki-2025",
  "donorName": "hiki hiki",
  "donorBirthDate": "2006-05-22T09:16:16.749Z",
  "donorBloodGroup": 8,
  "donorNIN": "125555879123412345"  
}
###


### Login:

POST {{host}}:{{port}}/auth/login
Content-Type: application/json
{
  "email": "hiki@example.com",
  "password": "Hiki-2025" 
}
###

GET {{host}}:{{port}}/auth/manage/info
Authorization: Bearer {{token}}
###



### User:

GET {{host}}:{{port}}/user/0196fd7f-3618-71fc-a348-680923b64576
###



@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMTk3MTdlNi00YmM0LTcwOWMtODhhZS1hMmNmMmJmNGMxOTMiLCJVc2VySWQiOiIwMTk3MTdlNi00YmM0LTcwOWMtODhhZS1hMmNmMmJmNGMxOTMiLCJlbWFpbCI6Imhpa2lAZXhhbXBsZS5jb20iLCJuYmYiOjE3NDg0NTI2ODAsImV4cCI6MTc0ODUzOTA4MCwiaWF0IjoxNzQ4NDUyNjgwLCJpc3MiOiJSZWREcm9wT3JnYW5pc2F0aW9uIiwiYXVkIjoiQmxvb2QgRG9uYXRvcnMifQ.GMUgrkeQmEBFNrcFKVuFtWoQyPrW7ypwpXBF_B7iu9U
GET {{host}}:{{port}}/user/
Authorization: Bearer {{token}}
###

###Users

GET {{host}}:{{port}}/users/
###

GET {{host}}:{{port}}/users/?PaginationTake=5&level=1
###

GET {{host}}:{{port}}/users/?CommuneId=558&PaginationTake=5&level=1
###

GET {{host}}:{{port}}/users/?WilayaId=16&PaginationTake=5&level=1
###

GET {{host}}:{{port}}/users/?DonorBloodGroup=7&PaginationTake=5&level=1
###

GET {{host}}:{{port}}/users/?DonorContactMethod=3&PaginationTake=5&level=1
###

GET {{host}}:{{port}}/users/?DonorWantToStayAnonymous=true&PaginationTake=5&level=1
###

GET {{host}}:{{port}}/users/?DonorExcludedFromPublicPortal=false&PaginationTake=5&level=1
###



### Enums:

//Enums
GET {{host}}:{{port}}/enums/BloodGroup,DonorAvailability,DonorContactMethod
###



### Wilayas,Communes:

GET {{host}}:{{port}}/Wilayas
###

GET {{host}}:{{port}}/Communes/16
###



### Blood Requests:

GET {{host}}:{{port}}/BloodDonationRequests
###

GET {{host}}:{{port}}/BloodDonationRequests?&wilayaId=16&PaginationTake=10&level=1
###

//Initiated = 0,Waiting = 1,PartiallyResolved = 2,Resolved = 3, Canceled = 4

GET {{host}}:{{port}}/BloodDonationRequests?evolutionStatus=Waiting&wilayaId=16&PaginationTake=10&level=1
###

GET {{host}}:{{port}}/BloodDonationRequests?PaginationTake=10&&PaginationSkip=10&level=1
###

GET {{host}}:{{port}}/BloodDonationRequests?PaginationTake=10&&PaginationSkip=20&level=1
###

GET {{host}}:{{port}}/BloodDonationRequests?PaginationTake=10&&PaginationSkip=30&level=1
###



### CTS:

GET {{host}}:{{port}}/BTC?&wilayaId=9&PaginationTake=10&level=1
###

GET {{host}}:{{port}}/BTC?PaginationTake=10&level=1
###

GET {{host}}:{{port}}/BTC?PaginationTake=10&&PaginationSkip=10&level=1
###

GET {{host}}:{{port}}/BTC?PaginationTake=10&&PaginationSkip=20&level=1
###

GET {{host}}:{{port}}/BTC?PaginationTake=10&&PaginationSkip=30&level=1
###


### Pledges:
GET {{host}}:{{port}}/Pledges
###

GET {{host}}:{{port}}/Pledges?PaginationTake=5&level=1
### 

@User1Id=0196fa27-4ca5-740f-ae1f-2620600d913e
@User2Id=0196fd7e-2d78-75ff-92ab-8c7f590e598c
@User3Id=0196fd7f-3618-71fc-a348-680923b64576
GET {{host}}:{{port}}/Pledges?UserId={{User1Id}}&PaginationTake=10&level=1
### 

GET {{host}}:{{port}}/Pledges?UserId={{User2Id}}&PaginationTake=10&level=1
### 

GET {{host}}:{{port}}/Pledges?UserId={{User3Id}}&PaginationTake=10&level=1
### 


GET {{host}}:{{port}}/Pledges?UserId={{User1Id}}&EvolutionStatus=0&PaginationTake=10&level=1
###  EvolutionStatus(0-5)

GET {{host}}:{{port}}/Pledges?UserId={{User2Id}}&EvolutionStatus=0&PaginationTake=10&level=1
### 

GET {{host}}:{{port}}/Pledges?UserId={{User3Id}}&EvolutionStatus=0&PaginationTake=10&level=1
### 


GET {{host}}:{{port}}/Pledges?UserId={{User1Id}}&EvolutionStatus=2&PaginationTake=10&level=1
###  EvolutionStatus(0-5)

GET {{host}}:{{port}}/Pledges?UserId={{User2Id}}&EvolutionStatus=1&PaginationTake=10&level=1
### 

GET {{host}}:{{port}}/Pledges?UserId={{User3Id}}&EvolutionStatus=4&PaginationTake=10&level=1
### 


@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMTk3MTdlNi00YmM0LTcwOWMtODhhZS1hMmNmMmJmNGMxOTMiLCJVc2VySWQiOiIwMTk3MTdlNi00YmM0LTcwOWMtODhhZS1hMmNmMmJmNGMxOTMiLCJlbWFpbCI6Imhpa2lAZXhhbXBsZS5jb20iLCJuYmYiOjE3NDg0NjI5MDcsImV4cCI6MTc0ODU0OTMwNywiaWF0IjoxNzQ4NDYyOTA3LCJpc3MiOiJSZWREcm9wT3JnYW5pc2F0aW9uIiwiYXVkIjoiQmxvb2QgRG9uYXRvcnMifQ.fpNQWK7eOs3Ub6O-SrpGK0kxsWVKEkbQdUOJfxG68rA
POST {{host}}:{{port}}/Pledges
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "bloodDonationRequestId": "facbb57b-1c39-c154-269c-d7323a866f1c",
  "pledgeDate": "2025-05-28T01:26:27.739Z",
  "pledgeNotes": "Notes"
}
### 0196fd7e-2d78-75ff-92ab-8c7f590e598c

POST {{host}}:{{port}}/Pledges
Content-Type: application/json
{
  "ApplicationUserId": "0196fd7f-3618-71fc-a348-680923b64576",
  "bloodDonationRequestId": "d94dd936-d026-2c8b-c679-a0c4c9938597",
  "pledgeDate": "2025-05-28T01:26:27.739Z",
  "pledgeNotes": "Notes de test"
}
###

// UserID: 0196fd7f-3618-71fc-a348-680923b64576
// Pid:    019701b1-540d-7d52-b2c7-d63d09e3b814

@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIwMTk3MTdlNi00YmM0LTcwOWMtODhhZS1hMmNmMmJmNGMxOTMiLCJVc2VySWQiOiIwMTk3MTdlNi00YmM0LTcwOWMtODhhZS1hMmNmMmJmNGMxOTMiLCJlbWFpbCI6Imhpa2lAZXhhbXBsZS5jb20iLCJuYmYiOjE3NDg0NjI5MDcsImV4cCI6MTc0ODU0OTMwNywiaWF0IjoxNzQ4NDYyOTA3LCJpc3MiOiJSZWREcm9wT3JnYW5pc2F0aW9uIiwiYXVkIjoiQmxvb2QgRG9uYXRvcnMifQ.fpNQWK7eOs3Ub6O-SrpGK0kxsWVKEkbQdUOJfxG68rA
PUT {{host}}:{{port}}/Pledges/60785249-90c0-ed55-fedd-8a229aaee083 
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "pledgeDate": "2025-05-30T01:26:27.739Z"
}
###



### BTC subscribed

@UserId = 0196fa27-4ca5-740f-ae1f-2620600d913e
GET {{host}}:{{port}}/BTC/subscribed?ApplicationUserId={{UserId}}&PaginationTake=10&level=1
###

GET {{host}}:{{port}}/BTC/subscribed?level=1
###


### Subscriptions

POST {{host}}:{{port}}/subscriptions
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "BloodTansfusionCenterId": "895bc690-3f2a-66c2-456f-ec56ae482558"
}
###

DELETE {{host}}:{{port}}/subscriptions/61d6696f-e81c-4e41-9d7f-ab1a97d4a7d7
Content-Type: application/json
{
  "ApplicationUserId": "0196fd7e-dad3-7d8e-bf2f-89b00e79ba37"
}
###


