//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BD.PublicPortal.Core
{

    public partial class BloodTansfusionCenterDTO
    {
        #region Constructors

        public BloodTansfusionCenterDTO() {
        }

        public BloodTansfusionCenterDTO(System.Guid id, string name, string address, string contact, string email, string tel, int wilayaId, List<DonorBloodTransferCenterSubscriptionsDTO> donorBloodTransferCenterSubscriptions, List<BloodDonationRequestDTO> bloodDonationRequests, WilayaDTO wilaya, List<BloodInventoryDTO> bloodInventories) {

          this.Id = id;
          this.Name = name;
          this.Address = address;
          this.Contact = contact;
          this.Email = email;
          this.Tel = tel;
          this.WilayaId = wilayaId;
          this.DonorBloodTransferCenterSubscriptions = donorBloodTransferCenterSubscriptions;
          this.BloodDonationRequests = bloodDonationRequests;
          this.Wilaya = wilaya;
          this.BloodInventories = bloodInventories;
        }

        #endregion

        #region Properties

        public System.Guid Id { get; set; }

        public string Name { get; set; }

        public string Address { get; set; }

        public string Contact { get; set; }

        public string Email { get; set; }

        public string Tel { get; set; }

        public int WilayaId { get; set; }

        #endregion

        #region Navigation Properties

        public List<DonorBloodTransferCenterSubscriptionsDTO> DonorBloodTransferCenterSubscriptions { get; set; }

        public List<BloodDonationRequestDTO> BloodDonationRequests { get; set; }

        public WilayaDTO Wilaya { get; set; }

        public List<BloodInventoryDTO> BloodInventories { get; set; }

        #endregion
    }

}
