//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BD.PublicPortal.Core
{

    public partial class BloodDonationPledgeDTO
    {
        #region Constructors

        public BloodDonationPledgeDTO() {
        }

        public BloodDonationPledgeDTO(System.Guid id, BloodDonationPladgeEvolutionStatus evolutionStatus, System.DateTime pledgeInitiatedDate, System.DateTime? pledgeDate, System.DateTime? pledgeHonoredOrCanceledDate, string pledgeNotes, string cantBeDoneReason, System.Guid bloodDonationRequestId, System.Guid applicationUserId, BloodDonationRequestDTO bloodDonationRequest, ApplicationUserDTO applicationUser) {

          this.Id = id;
          this.EvolutionStatus = evolutionStatus;
          this.PledgeInitiatedDate = pledgeInitiatedDate;
          this.PledgeDate = pledgeDate;
          this.PledgeHonoredOrCanceledDate = pledgeHonoredOrCanceledDate;
          this.PledgeNotes = pledgeNotes;
          this.CantBeDoneReason = cantBeDoneReason;
          this.BloodDonationRequestId = bloodDonationRequestId;
          this.ApplicationUserId = applicationUserId;
          this.BloodDonationRequest = bloodDonationRequest;
          this.ApplicationUser = applicationUser;
        }

        #endregion

        #region Properties

        public System.Guid Id { get; set; }

        public BloodDonationPladgeEvolutionStatus EvolutionStatus { get; set; }

        public System.DateTime PledgeInitiatedDate { get; set; }

        public System.DateTime? PledgeDate { get; set; }

        public System.DateTime? PledgeHonoredOrCanceledDate { get; set; }

        public string PledgeNotes { get; set; }

        public string CantBeDoneReason { get; set; }

        public System.Guid BloodDonationRequestId { get; set; }

        public System.Guid ApplicationUserId { get; set; }

        #endregion

        #region Navigation Properties

        public BloodDonationRequestDTO BloodDonationRequest { get; set; }

        public ApplicationUserDTO ApplicationUser { get; set; }

        #endregion
    }

}
