//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace BD.PublicPortal.Core
{

    public static partial class BloodDonationPledgeConverter
    {

        public static BloodDonationPledgeDTO ToDto(this BloodDonationPledge source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static BloodDonationPledgeDTO ToDtoWithRelated(this BloodDonationPledge source, int level)
        {
            if (source == null)
              return null;

            var target = new BloodDonationPledgeDTO();

            // Properties
            target.Id = source.Id;
            target.EvolutionStatus = source.EvolutionStatus;
            target.PledgeInitiatedDate = source.PledgeInitiatedDate;
            target.PledgeDate = source.PledgeDate;
            target.PledgeHonoredOrCanceledDate = source.PledgeHonoredOrCanceledDate;
            target.PledgeNotes = source.PledgeNotes;
            target.CantBeDoneReason = source.CantBeDoneReason;
            target.BloodDonationRequestId = source.BloodDonationRequestId;
            target.ApplicationUserId = source.ApplicationUserId;

            // Navigation Properties
            if (level > 0) {
              target.BloodDonationRequest = source.BloodDonationRequest.ToDtoWithRelated(level - 1);
              target.ApplicationUser = source.ApplicationUser.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BloodDonationPledge ToEntity(this BloodDonationPledgeDTO source)
        {
            if (source == null)
              return null;

            var target = new BloodDonationPledge();

            // Properties
            target.Id = source.Id;
            target.EvolutionStatus = source.EvolutionStatus;
            target.PledgeInitiatedDate = source.PledgeInitiatedDate;
            target.PledgeDate = source.PledgeDate;
            target.PledgeHonoredOrCanceledDate = source.PledgeHonoredOrCanceledDate;
            target.PledgeNotes = source.PledgeNotes;
            target.CantBeDoneReason = source.CantBeDoneReason;
            target.BloodDonationRequestId = source.BloodDonationRequestId;
            target.ApplicationUserId = source.ApplicationUserId;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<BloodDonationPledgeDTO> ToDtos(this IEnumerable<BloodDonationPledge> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<BloodDonationPledgeDTO> ToDtosWithRelated(this IEnumerable<BloodDonationPledge> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BloodDonationPledge> ToEntities(this IEnumerable<BloodDonationPledgeDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BloodDonationPledge source, BloodDonationPledgeDTO target);

        static partial void OnEntityCreating(BloodDonationPledgeDTO source, BloodDonationPledge target);

    }

}
