//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace BD.PublicPortal.Core
{

    public static partial class DonorBloodTransferCenterSubscriptionsConverter
    {

        public static DonorBloodTransferCenterSubscriptionsDTO ToDto(this DonorBloodTransferCenterSubscriptions source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DonorBloodTransferCenterSubscriptionsDTO ToDtoWithRelated(this DonorBloodTransferCenterSubscriptions source, int level)
        {
            if (source == null)
              return null;

            var target = new DonorBloodTransferCenterSubscriptionsDTO();

            // Properties
            target.Id = source.Id;
            target.BloodTansfusionCenterId = source.BloodTansfusionCenterId;
            target.ApplicationUserId = source.ApplicationUserId;

            // Navigation Properties
            if (level > 0) {
              target.BloodTansfusionCenter = source.BloodTansfusionCenter.ToDtoWithRelated(level - 1);
              target.ApplicationUser = source.ApplicationUser.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static DonorBloodTransferCenterSubscriptions ToEntity(this DonorBloodTransferCenterSubscriptionsDTO source)
        {
            if (source == null)
              return null;

            var target = new DonorBloodTransferCenterSubscriptions();

            // Properties
            target.Id = source.Id;
            target.BloodTansfusionCenterId = source.BloodTansfusionCenterId;
            target.ApplicationUserId = source.ApplicationUserId;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DonorBloodTransferCenterSubscriptionsDTO> ToDtos(this IEnumerable<DonorBloodTransferCenterSubscriptions> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DonorBloodTransferCenterSubscriptionsDTO> ToDtosWithRelated(this IEnumerable<DonorBloodTransferCenterSubscriptions> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<DonorBloodTransferCenterSubscriptions> ToEntities(this IEnumerable<DonorBloodTransferCenterSubscriptionsDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(DonorBloodTransferCenterSubscriptions source, DonorBloodTransferCenterSubscriptionsDTO target);

        static partial void OnEntityCreating(DonorBloodTransferCenterSubscriptionsDTO source, DonorBloodTransferCenterSubscriptions target);

    }

}
