//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BD.PublicPortal.Core
{

    public partial class DonorBloodTransferCenterSubscriptionsDTO
    {
        #region Constructors

        public DonorBloodTransferCenterSubscriptionsDTO() {
        }

        public DonorBloodTransferCenterSubscriptionsDTO(System.Guid id, System.Guid bloodTansfusionCenterId, System.Guid applicationUserId, BloodTansfusionCenterDTO bloodTansfusionCenter, ApplicationUserDTO applicationUser) {

          this.Id = id;
          this.BloodTansfusionCenterId = bloodTansfusionCenterId;
          this.ApplicationUserId = applicationUserId;
          this.BloodTansfusionCenter = bloodTansfusionCenter;
          this.ApplicationUser = applicationUser;
        }

        #endregion

        #region Properties

        public System.Guid Id { get; set; }

        public System.Guid BloodTansfusionCenterId { get; set; }

        public System.Guid ApplicationUserId { get; set; }

        #endregion

        #region Navigation Properties

        public BloodTansfusionCenterDTO BloodTansfusionCenter { get; set; }

        public ApplicationUserDTO ApplicationUser { get; set; }

        #endregion
    }

}
