//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22-05-2025 07:35:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BD.PublicPortal.Core
{
    public partial class BloodDonationRequest : EntityBase<Guid>, IAggregateRoot {

        public BloodDonationRequest()
        {
            this.BloodDonationPledges = new List<BloodDonationPledge>();
            OnCreated();
        }

        public Guid Id { get; set; }

        public BloodDonationRequestEvolutionStatus? EvolutionStatus { get; set; }

        public BloodDonationType DonationType { get; set; }

        public BloodGroup BloodGroup { get; set; }

        public int RequestedQty { get; set; }

        public DateTime RequestDate { get; set; }

        public DateTime? RequestDueDate { get; set; }

        public BloodDonationRequestPriority Priority { get; set; }

        public string MoreDetails { get; set; }

        public string ServiceName { get; set; }

        public Guid BloodTansfusionCenterId { get; set; }

        public virtual IList<BloodDonationPledge> BloodDonationPledges { get; set; }

        public virtual BloodTansfusionCenter BloodTansfusionCenter { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
