//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BD.PublicPortal.Core
{
    public partial class Wilaya : EntityBase<int>, IAggregateRoot {

        public Wilaya()
        {
            this.BloodTansfusionCenters = new List<BloodTansfusionCenter>();
            this.Communes = new List<Commune>();
            OnCreated();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public virtual IList<BloodTansfusionCenter> BloodTansfusionCenters { get; set; }

        public virtual IList<Commune> Communes { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
