//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BD.PublicPortal.Core
{
    public enum BloodDonationRequestEvolutionStatus : int
    {
        Initiated = 0,
        [System.ComponentModel.DataAnnotations.Display(Name = @"En Attente")]
        Waiting = 1,
        [System.ComponentModel.DataAnnotations.Display(Name = @"Partiellement Résolu")]
        PartiallyResolved = 2,
        Resolved = 3,
        Canceled = 4
    }
}
