//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BD.PublicPortal.Core
{
    public enum BloodGroup : int
    {
        AB_POSITIVE = 1,
        AB_NEGATIVE = 2,
        A_POSITIVE = 3,
        A_NEGATIVE = 4,
        B_POSITIVE = 5,
        B_NEGATIVE = 6,
        O_POSITIVE = 7,
        O_NEGATIVE = 8
    }
}
