//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BD.BloodTransfusionCenter.Core
{
    /// <summary>
    /// There are no comments for BloodDonationConfiguration in the schema.
    /// </summary>
    public partial class BloodDonationConfiguration : IEntityTypeConfiguration<BloodDonation>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<BloodDonation> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<BloodDonation> builder)
        {
            builder.ToTable(@"BloodDonations");
            builder.Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.DonationStatus).HasColumnName(@"DonationStatus").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DonationDate).HasColumnName(@"DonationDate").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Type).HasColumnName(@"Type").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Group).HasColumnName(@"Group").ValueGeneratedNever();
            builder.Property(x => x.LotNumber).HasColumnName(@"LotNumber").ValueGeneratedNever();
            builder.Property(x => x.DonorId).HasColumnName(@"DonorId").ValueGeneratedNever();
            builder.Property(x => x.BloodDonationRequestId).HasColumnName(@"BloodDonationRequestId").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasOne(x => x.Donor).WithMany(op => op.BloodDonations).OnDelete(DeleteBehavior.Restrict).HasForeignKey(@"DonorId").IsRequired(true);
            builder.HasOne(x => x.BloodDonationRequest).WithMany(op => op.BloodDonations).OnDelete(DeleteBehavior.Restrict).HasForeignKey(@"BloodDonationRequestId").IsRequired(false);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<BloodDonation> builder);

        #endregion
    }

}
