//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BD.BloodTransfusionCenter.Core
{

    public partial class Model : DbContext
    {

        public Model() :
            base()
        {
            OnCreated();
        }

        public Model(DbContextOptions<Model> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<BloodDonationRequest> BloodDonationRequests
        {
            get;
            set;
        }

        public virtual DbSet<Service> Services
        {
            get;
            set;
        }

        public virtual DbSet<Donor> Donors
        {
            get;
            set;
        }

        public virtual DbSet<BloodDonation> BloodDonations
        {
            get;
            set;
        }

        public virtual DbSet<BloodTansfusionCenter> BloodTansfusionCenters
        {
            get;
            set;
        }

        public virtual DbSet<Wilaya> Wilayas
        {
            get;
            set;
        }

        public virtual DbSet<BloodDonationPledgeExtended> BloodDonationPledgeExtendeds
        {
            get;
            set;
        }

        public virtual DbSet<BloodInventory> BloodInventories
        {
            get;
            set;
        }

        public virtual DbSet<BloodOutOperation> BloodOutOperations
        {
            get;
            set;
        }

        public virtual DbSet<Commune> Communes
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration<BloodDonationRequest>(new BloodDonationRequestConfiguration());
            modelBuilder.ApplyConfiguration<Service>(new ServiceConfiguration());
            modelBuilder.ApplyConfiguration<Donor>(new DonorConfiguration());
            modelBuilder.ApplyConfiguration<BloodDonation>(new BloodDonationConfiguration());
            modelBuilder.ApplyConfiguration<BloodTansfusionCenter>(new BloodTansfusionCenterConfiguration());
            modelBuilder.ApplyConfiguration<Wilaya>(new WilayaConfiguration());
            modelBuilder.ApplyConfiguration<BloodDonationPledgeExtended>(new BloodDonationPledgeExtendedConfiguration());
            modelBuilder.ApplyConfiguration<BloodInventory>(new BloodInventoryConfiguration());
            modelBuilder.ApplyConfiguration<BloodOutOperation>(new BloodOutOperationConfiguration());
            modelBuilder.ApplyConfiguration<Commune>(new CommuneConfiguration());
            CustomizeMapping(ref modelBuilder);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
