//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BD.BloodTransfusionCenter.Core
{

    public partial class BloodDonationRequestDTO
    {
        #region Constructors

        public BloodDonationRequestDTO() {
        }

        public BloodDonationRequestDTO(System.Guid id, BloodDonationRequestEvolutionStatus? evolutionStatus, BloodDonationType donationType, BloodGroup bloodGroup, int requestedQty, System.DateTime requestDate, System.DateTime? requestDueDate, BloodDonationRequestPriority priority, string moreDetails, System.Guid? serviceId, ServiceDTO service, List<BloodDonationPledgeExtendedDTO> bloodDonationPledges, List<BloodDonationDTO> bloodDonations) {

          this.Id = id;
          this.EvolutionStatus = evolutionStatus;
          this.DonationType = donationType;
          this.BloodGroup = bloodGroup;
          this.RequestedQty = requestedQty;
          this.RequestDate = requestDate;
          this.RequestDueDate = requestDueDate;
          this.Priority = priority;
          this.MoreDetails = moreDetails;
          this.ServiceId = serviceId;
          this.Service = service;
          this.BloodDonationPledges = bloodDonationPledges;
          this.BloodDonations = bloodDonations;
        }

        #endregion

        #region Properties

        public System.Guid Id { get; set; }

        public BloodDonationRequestEvolutionStatus? EvolutionStatus { get; set; }

        public BloodDonationType DonationType { get; set; }

        public BloodGroup BloodGroup { get; set; }

        public int RequestedQty { get; set; }

        public System.DateTime RequestDate { get; set; }

        public System.DateTime? RequestDueDate { get; set; }

        public BloodDonationRequestPriority Priority { get; set; }

        public string MoreDetails { get; set; }

        public System.Guid? ServiceId { get; set; }

        #endregion

        #region Navigation Properties

        public ServiceDTO Service { get; set; }

        public List<BloodDonationPledgeExtendedDTO> BloodDonationPledges { get; set; }

        public List<BloodDonationDTO> BloodDonations { get; set; }

        #endregion
    }

}
