//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace BD.BloodTransfusionCenter.Core
{

    public static partial class BloodDonationPledgeExtendedConverter
    {

        public static BloodDonationPledgeExtendedDTO ToDto(this BloodDonationPledgeExtended source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static BloodDonationPledgeExtendedDTO ToDtoWithRelated(this BloodDonationPledgeExtended source, int level)
        {
            if (source == null)
              return null;

            var target = new BloodDonationPledgeExtendedDTO();

            // Properties
            target.Id = source.Id;
            target.EvolutionStatus = source.EvolutionStatus;
            target.PledgeInitiatedDate = source.PledgeInitiatedDate;
            target.PledgeEffectiveDate = source.PledgeEffectiveDate;
            target.PledgeHonoredOrCanceledDate = source.PledgeHonoredOrCanceledDate;
            target.CantBeDoneReason = source.CantBeDoneReason;
            target.DonorCorrelationId = source.DonorCorrelationId;
            target.DonorName = source.DonorName;
            target.DonorBirthDate = source.DonorBirthDate;
            target.DonorBloodGroup = source.DonorBloodGroup;
            target.DonorNIN = source.DonorNIN;
            target.DonorTel = source.DonorTel;
            target.DonorEmail = source.DonorEmail;
            target.DonorNotes = source.DonorNotes;
            target.DonorLastDonationDate = source.DonorLastDonationDate;
            target.BloodDonationRequestId = source.BloodDonationRequestId;

            // Navigation Properties
            if (level > 0) {
              target.BloodDonationRequest = source.BloodDonationRequest.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BloodDonationPledgeExtended ToEntity(this BloodDonationPledgeExtendedDTO source)
        {
            if (source == null)
              return null;

            var target = new BloodDonationPledgeExtended();

            // Properties
            target.Id = source.Id;
            target.EvolutionStatus = source.EvolutionStatus;
            target.PledgeInitiatedDate = source.PledgeInitiatedDate;
            target.PledgeEffectiveDate = source.PledgeEffectiveDate;
            target.PledgeHonoredOrCanceledDate = source.PledgeHonoredOrCanceledDate;
            target.CantBeDoneReason = source.CantBeDoneReason;
            target.DonorCorrelationId = source.DonorCorrelationId;
            target.DonorName = source.DonorName;
            target.DonorBirthDate = source.DonorBirthDate;
            target.DonorBloodGroup = source.DonorBloodGroup;
            target.DonorNIN = source.DonorNIN;
            target.DonorTel = source.DonorTel;
            target.DonorEmail = source.DonorEmail;
            target.DonorNotes = source.DonorNotes;
            target.DonorLastDonationDate = source.DonorLastDonationDate;
            target.BloodDonationRequestId = source.BloodDonationRequestId;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<BloodDonationPledgeExtendedDTO> ToDtos(this IEnumerable<BloodDonationPledgeExtended> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<BloodDonationPledgeExtendedDTO> ToDtosWithRelated(this IEnumerable<BloodDonationPledgeExtended> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BloodDonationPledgeExtended> ToEntities(this IEnumerable<BloodDonationPledgeExtendedDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BloodDonationPledgeExtended source, BloodDonationPledgeExtendedDTO target);

        static partial void OnEntityCreating(BloodDonationPledgeExtendedDTO source, BloodDonationPledgeExtended target);

    }

}
