//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BD.BloodTransfusionCenter.Core
{

    public partial class BloodInventoryDTO
    {
        #region Constructors

        public BloodInventoryDTO() {
        }

        public BloodInventoryDTO(System.Guid id, BloodGroup bloodGroup, BloodDonationType bloodDonationType, int? totalQty, int? minQty, int? maxQty) {

          this.Id = id;
          this.BloodGroup = bloodGroup;
          this.BloodDonationType = bloodDonationType;
          this.TotalQty = totalQty;
          this.MinQty = minQty;
          this.MaxQty = maxQty;
        }

        #endregion

        #region Properties

        public System.Guid Id { get; set; }

        public BloodGroup BloodGroup { get; set; }

        public BloodDonationType BloodDonationType { get; set; }

        public int? TotalQty { get; set; }

        public int? MinQty { get; set; }

        public int? MaxQty { get; set; }

        #endregion
    }

}
