//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BD.BloodTransfusionCenter.Core
{

    public partial class CommuneDTO
    {
        #region Constructors

        public CommuneDTO() {
        }

        public CommuneDTO(int id, string name, int wilayaId, WilayaDTO wilaya, List<DonorDTO> donors) {

          this.Id = id;
          this.Name = name;
          this.WilayaId = wilayaId;
          this.Wilaya = wilaya;
          this.Donors = donors;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public string Name { get; set; }

        public int WilayaId { get; set; }

        #endregion

        #region Navigation Properties

        public WilayaDTO Wilaya { get; set; }

        public List<DonorDTO> Donors { get; set; }

        #endregion
    }

}
