//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace BD.BloodTransfusionCenter.Core
{

    public static partial class ServiceConverter
    {

        public static ServiceDTO ToDto(this Service source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ServiceDTO ToDtoWithRelated(this Service source, int level)
        {
            if (source == null)
              return null;

            var target = new ServiceDTO();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.BloodCentralPlatformId = source.BloodCentralPlatformId;

            // Navigation Properties
            if (level > 0) {
              target.BloodDonationRequests = source.BloodDonationRequests.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Service ToEntity(this ServiceDTO source)
        {
            if (source == null)
              return null;

            var target = new Service();

            // Properties
            target.Id = source.Id;
            target.Name = source.Name;
            target.BloodCentralPlatformId = source.BloodCentralPlatformId;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ServiceDTO> ToDtos(this IEnumerable<Service> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ServiceDTO> ToDtosWithRelated(this IEnumerable<Service> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Service> ToEntities(this IEnumerable<ServiceDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Service source, ServiceDTO target);

        static partial void OnEntityCreating(ServiceDTO source, Service target);

    }

}
