//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 21-05-2025 19:15:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace BD.BloodTransfusionCenter.Core
{

    public partial class WilayaDTO
    {
        #region Constructors

        public WilayaDTO() {
        }

        public WilayaDTO(int id, string name, List<CommuneDTO> communes, List<BloodTansfusionCenterDTO> bloodTansfusionCenters) {

          this.Id = id;
          this.Name = name;
          this.Communes = communes;
          this.BloodTansfusionCenters = bloodTansfusionCenters;
        }

        #endregion

        #region Properties

        public int Id { get; set; }

        public string Name { get; set; }

        #endregion

        #region Navigation Properties

        public List<CommuneDTO> Communes { get; set; }

        public List<BloodTansfusionCenterDTO> BloodTansfusionCenters { get; set; }

        #endregion
    }

}
