//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BD.PublicPortal.Core
{
    /// <summary>
    /// There are no comments for ApplicationUserConfiguration in the schema.
    /// </summary>
    public partial class ApplicationUserConfiguration : IEntityTypeConfiguration<ApplicationUser>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<ApplicationUser> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<ApplicationUser> builder)
        {
            builder.ToTable(@"ApplicationUsers");
            builder.Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.CorrelationId).HasColumnName(@"CorrelationId").ValueGeneratedNever();
            builder.Property(x => x.IsAdmin).HasColumnName(@"IsAdmin").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DonorWantToStayAnonymous).HasColumnName(@"DonorWantToStayAnonymous").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DonorExcludeFromPublicPortal).HasColumnName(@"DonorExcludeFromPublicPortal").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DonorAvailability).HasColumnName(@"DonorAvailability").ValueGeneratedNever();
            builder.Property(x => x.DonorContactMethod).HasColumnName(@"DonorContactMethod").ValueGeneratedNever();
            builder.Property(x => x.DonorName).HasColumnName(@"DonorName").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DonorBirthDate).HasColumnName(@"DonorBirthDate").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DonorBloodGroup).HasColumnName(@"DonorBloodGroup").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DonorNIN).HasColumnName(@"DonorNIN").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DonorTel).HasColumnName(@"DonorTel").ValueGeneratedNever();
            builder.Property(x => x.DonorNotesForBTC).HasColumnName(@"DonorNotesForBTC").ValueGeneratedNever();
            builder.Property(x => x.DonorLastDonationDate).HasColumnName(@"DonorLastDonationDate").ValueGeneratedNever();
            builder.Property(x => x.CommuneId).HasColumnName(@"CommuneId").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasMany(x => x.DonorBloodTransferCenterSubscriptions).WithOne(op => op.ApplicationUser).HasForeignKey(@"ApplicationUserId").IsRequired(true);
            builder.HasMany(x => x.BloodDonationPledges).WithOne(op => op.ApplicationUser).HasForeignKey(@"ApplicationUserId").IsRequired(true);
            builder.HasOne(x => x.Commune).WithMany(op => op.ApplicationUsers).HasForeignKey(@"CommuneId").IsRequired(false);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<ApplicationUser> builder);

        #endregion
    }

}
