//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22-05-2025 07:35:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BD.PublicPortal.Core
{
    /// <summary>
    /// There are no comments for BloodDonationRequestConfiguration in the schema.
    /// </summary>
    public partial class BloodDonationRequestConfiguration : IEntityTypeConfiguration<BloodDonationRequest>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<BloodDonationRequest> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<BloodDonationRequest> builder)
        {
            builder.ToTable(@"BloodDonationRequests");
            builder.Property(x => x.Id).HasColumnName(@"Id").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EvolutionStatus).HasColumnName(@"EvolutionStatus").ValueGeneratedNever();
            builder.Property(x => x.DonationType).HasColumnName(@"DonationType").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.BloodGroup).HasColumnName(@"BloodGroup").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RequestedQty).HasColumnName(@"RequestedQty").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RequestDate).HasColumnName(@"RequestDate").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.RequestDueDate).HasColumnName(@"RequestDueDate").ValueGeneratedNever();
            builder.Property(x => x.Priority).HasColumnName(@"Priority").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.MoreDetails).HasColumnName(@"MoreDetails").ValueGeneratedNever();
            builder.Property(x => x.ServiceName).HasColumnName(@"ServiceName").ValueGeneratedNever();
            builder.Property(x => x.BloodTansfusionCenterId).HasColumnName(@"BloodTansfusionCenterId").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasMany(x => x.BloodDonationPledges).WithOne(op => op.BloodDonationRequest).HasForeignKey(@"BloodDonationRequestId").IsRequired(true);
            builder.HasOne(x => x.BloodTansfusionCenter).WithMany(op => op.BloodDonationRequests).HasForeignKey(@"BloodTansfusionCenterId").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<BloodDonationRequest> builder);

        #endregion
    }

}
